optimizedBT: optimizedBT.o
	gcc -std=c11 optimizedBT.c -o optimizedBT -O3

optimizedBTBench: optimizedBT.o
	gcc -std=c11 optimizedBT.c -o optimizedBTBench -O3 -DNDEBUG

greedyByIntersections: greedyByIntersections.o
	gcc -std=c11 greedyByIntersections.c -o greedyByIntersections -O3

greedyByIntersectionsBench: greedyByIntersections.o
	gcc -std=c11 greedyByIntersections.c -o greedyByIntersectionsBench -O3 -DNDEBUG