backtracking: backtracking.o
	gcc -std=c11 backtracking.c -o backtracking -O3

optimizedBT: optimizedBT.o
	gcc -std=c11 optimizedBT.c -o optimizedBT -O3

geometric: geometric.o
	gcc -std=c11 geometric.c -o geometric -O3

greedy: greedy.o
	gcc -std=c11 greedy.c -o greedy -O3

geometricGreedy: geometricGreedy.o
	gcc -std=c11 geometricGreedy.c -o geometricGreedy -O3

greedyByIntersections: greedyByIntersections.o
	gcc -std=c11 greedyByIntersections.c -o greedyByIntersections -O3